"""create demo tables

Revision ID: 50b75ce1aba2
Revises: 
Create Date: 2026-08-17 13:43:00.394917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b75ce1aba2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_date'), ['date'], unique=False)

    op.create_table('daily_summary',
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('total_kcal', sa.REAL(), nullable=True),
    sa.Column('total_carb_g', sa.REAL(), nullable=True),
    sa.Column('total_protein_g', sa.REAL(), nullable=True),
    sa.Column('total_fat_g', sa.REAL(), nullable=True),
    sa.Column('total_fiber_g', sa.REAL(), nullable=True),
    sa.Column('bmr_snapshot', sa.REAL(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('food_base_cn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_code', sa.Text(), nullable=False),
    sa.Column('food_name', sa.Text(), nullable=False),
    sa.Column('edible_pct', sa.REAL(), nullable=True),
    sa.Column('kcal_100g', sa.REAL(), nullable=True),
    sa.Column('carb_100g', sa.REAL(), nullable=True),
    sa.Column('protein_100g', sa.REAL(), nullable=True),
    sa.Column('fat_100g', sa.REAL(), nullable=True),
    sa.Column('fiber_100g', sa.REAL(), nullable=True),
    sa.Column('source_commit', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_code', 'source_commit', name='uq_food_base_cn_code_commit')
    )
    with op.batch_alter_table('food_base_cn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_base_cn_food_code'), ['food_code'], unique=False)

    op.create_table('food_base_us',
    sa.Column('fdc_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kcal_100g', sa.REAL(), nullable=True),
    sa.Column('carb_100g', sa.REAL(), nullable=True),
    sa.Column('protein_100g', sa.REAL(), nullable=True),
    sa.Column('fat_100g', sa.REAL(), nullable=True),
    sa.Column('fiber_100g', sa.REAL(), nullable=True),
    sa.Column('cached_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('fdc_id')
    )
    op.create_table('meal_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('meal_slot', sa.Enum('breakfast', 'lunch', 'dinner', 'other', name='ck_meal_entry_meal_slot', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('food_name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.REAL(), nullable=False),
    sa.Column('unit', sa.Enum('g', 'serving', name='ck_meal_entry_unit', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('kcal', sa.REAL(), nullable=True),
    sa.Column('carb_g', sa.REAL(), nullable=True),
    sa.Column('protein_g', sa.REAL(), nullable=True),
    sa.Column('fat_g', sa.REAL(), nullable=True),
    sa.Column('fiber_g', sa.REAL(), nullable=True),
    sa.Column('source_tag', sa.Enum('chn_table', 'usda', 'decompose_estimate', 'user_create', name='ck_meal_entry_source_tag', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_entry_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_entry_date'))

    op.drop_table('meal_entry')
    op.drop_table('food_base_us')
    with op.batch_alter_table('food_base_cn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_base_cn_food_code'))

    op.drop_table('food_base_cn')
    op.drop_table('daily_summary')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_date'))

    op.drop_table('chat_message')
    # ### end Alembic commands ###
